-- NOTE: transcribed from screenshots of the real generated script, so it now
-- matches inputSimple.yaml and examplecos.sql as a complete triple. The
-- previous copy of this fixture was a snippet from a different project.
-- Worth a spot-check against the original before treating it as exact.

-- Note: Projects-side OPENQUERY script written by generative AI

USE PROJECTD93A5E7;

DECLARE @ScriptStartTime DATETIME2 = SYSDATETIME();
PRINT 'Projects script start at ' +
    CONVERT(VARCHAR(30), @ScriptStartTime, 126);

    /* Generated by Python (Kilo Code, PK-simple) from simplified cohorts YAML
       Cohort (Projects): PKTable (PK)
       Destination: PROJECTS.PROJECTD93A5E7.dbo.PKTable2
       Source global temp (Cosmos): ##JVM_PKTable2 via OPENQUERY
    */

    DECLARE @StartTime_PKTable2 DATETIME2 = SYSDATETIME();
    PRINT 'Projects cohort start: PKTable (PKTable2) at ' +
        CONVERT(VARCHAR(30), @StartTime_PKTable2, 126);

/* Generated by Python (Kilo Code, PK-simple) from simplified cohorts YAML
   Cohort (Projects): PKTable (PK)
   Destination: PROJECTS.PROJECTD93A5E7.dbo.PKTable2
   Source global temp (Cosmos): ##JVM_PKTable2 via OPENQUERY
*/

    USE PROJECTD93A5E7;

-- Drop and recreate destination table so schema is always aligned with this script
DROP TABLE IF EXISTS PROJECTD93A5E7.dbo.PKTable2;

CREATE TABLE PROJECTD93A5E7.dbo.PKTable2
(
PatientDurableKey    BIGINT      NOT NULL
);

-- Local temp table to receive data from Cosmos via OPENQUERY
DROP TABLE IF EXISTS #Local_PKTable2;

SELECT
    PatientDurableKey
INTO #Local_PKTable2
FROM OPENQUERY(
    [et4003vpdsql032],
    '
        SELECT
            PatientDurableKey
        FROM ##JVM_PKTable2
    '
);

-- Insert into destination table
INSERT INTO PROJECTD93A5E7.dbo.PKTable2 (PatientDurableKey)
SELECT PatientDurableKey
FROM #Local_PKTable2;

-- Cosmos-side row count for PKTable2 (##JVM_PKTable2)
SELECT
    'PKTable2' AS CohortName,
    COUNT(*) AS CosmosRowCount
FROM OPENQUERY(
    [et4003vpdsql032],
    '
        SELECT
            1 AS dummy
        FROM ##JVM_PKTable2
    '
);

-- Projects-side row count for PKTable2
SELECT
    'PKTable2' AS TableName,
    COUNT(*) AS PKTable2RowCount
FROM PROJECTD93A5E7.dbo.PKTable2;

-- Sample rows for PKTable2
SELECT TOP (1) *
FROM PROJECTD93A5E7.dbo.PKTable2;

    DECLARE @EndTime_PKTable2 DATETIME2 = SYSDATETIME();
    PRINT 'Projects cohort end: PKTable (PKTable2) at ' +
        CONVERT(VARCHAR(30), @EndTime_PKTable2, 126);

    DECLARE @ElapsedSeconds_PKTable2 INT =
        DATEDIFF(SECOND, @StartTime_PKTable2, @EndTime_PKTable2);
    DECLARE @ElapsedMinutes_PKTable2 INT = @ElapsedSeconds_PKTable2 / 60;
    DECLARE @RemainingSeconds_PKTable2 INT = @ElapsedSeconds_PKTable2 % 60;

    PRINT 'Projects cohort duration (seconds): ' +
        CONVERT(VARCHAR(30), @ElapsedSeconds_PKTable2);

    PRINT 'Projects cohort duration (minutes:seconds): ' +
        CONVERT(VARCHAR(30), @ElapsedMinutes_PKTable2) + 'm ' +
        CONVERT(VARCHAR(30), @RemainingSeconds_PKTable2) + 's';

    /* Generated by Python (Kilo Code, PK-simple) from simplified cohorts YAML
       Cohort (Projects): PKTable (PK)
       Destination: PROJECTS.PROJECTD93A5E7.dbo.PKTable
       Source global temp (Cosmos): ##JVM_PKTable via OPENQUERY
    */

    DECLARE @StartTime_PKTable DATETIME2 = SYSDATETIME();
    PRINT 'Projects cohort start: PKTable (PKTable) at ' +
        CONVERT(VARCHAR(30), @StartTime_PKTable, 126);

/* Generated by Python (Kilo Code, PK-simple) from simplified cohorts YAML
   Cohort (Projects): PKTable (PK)
   Destination: PROJECTS.PROJECTD93A5E7.dbo.PKTable
   Source global temp (Cosmos): ##JVM_PKTable via OPENQUERY
*/

    USE PROJECTD93A5E7;

-- Drop and recreate destination table so schema is always aligned with this script
DROP TABLE IF EXISTS PROJECTD93A5E7.dbo.PKTable;

CREATE TABLE PROJECTD93A5E7.dbo.PKTable
(
DiagnosisEventKey    BIGINT      NOT NULL,
PatientDurableKey    BIGINT      NOT NULL,
EncounterKey         BIGINT      NOT NULL,
StartDateKey         INT         NOT NULL,
BillingCodeValue     VARCHAR(400)    NULL,
BillingCodeType      VARCHAR(100)    NULL
);

-- Local temp table to receive data from Cosmos via OPENQUERY
DROP TABLE IF EXISTS #Local_PKTable;

SELECT
    DiagnosisEventKey, PatientDurableKey, EncounterKey, StartDateKey,
    BillingCodeValue, BillingCodeType
INTO #Local_PKTable
FROM OPENQUERY(
    [et4003vpdsql032],
    '
        SELECT
            DiagnosisEventKey, PatientDurableKey, EncounterKey, StartDateKey,
            BillingCodeValue, BillingCodeType
        FROM ##JVM_PKTable
    '
);

-- Insert into destination table
INSERT INTO PROJECTD93A5E7.dbo.PKTable (DiagnosisEventKey, PatientDurableKey,
    EncounterKey, StartDateKey, BillingCodeValue, BillingCodeType)
SELECT DiagnosisEventKey, PatientDurableKey, EncounterKey, StartDateKey,
    BillingCodeValue, BillingCodeType
FROM #Local_PKTable;

-- Cosmos-side row count for PKTable (##JVM_PKTable)
SELECT
    'PKTable' AS CohortName,
    COUNT(*) AS CosmosRowCount
FROM OPENQUERY(
    [et4003vpdsql032],
    '
        SELECT
            1 AS dummy
        FROM ##JVM_PKTable
    '
);

-- Projects-side row count for PKTable
SELECT
    'PKTable' AS TableName,
    COUNT(*) AS PKTableRowCount
FROM PROJECTD93A5E7.dbo.PKTable;

-- Sample rows for PKTable
SELECT TOP (1) *
FROM PROJECTD93A5E7.dbo.PKTable;

    DECLARE @EndTime_PKTable DATETIME2 = SYSDATETIME();
    PRINT 'Projects cohort end: PKTable (PKTable) at ' +
        CONVERT(VARCHAR(30), @EndTime_PKTable, 126);

    DECLARE @ElapsedSeconds_PKTable INT =
        DATEDIFF(SECOND, @StartTime_PKTable, @EndTime_PKTable);
    DECLARE @ElapsedMinutes_PKTable INT = @ElapsedSeconds_PKTable / 60;
    DECLARE @RemainingSeconds_PKTable INT = @ElapsedSeconds_PKTable % 60;

    PRINT 'Projects cohort duration (seconds): ' +
        CONVERT(VARCHAR(30), @ElapsedSeconds_PKTable);

    PRINT 'Projects cohort duration (minutes:seconds): ' +
        CONVERT(VARCHAR(30), @ElapsedMinutes_PKTable) + 'm ' +
        CONVERT(VARCHAR(30), @RemainingSeconds_PKTable) + 's';

DECLARE @ScriptEndTime DATETIME2 = SYSDATETIME();
PRINT 'Projects script end at ' +
    CONVERT(VARCHAR(30), @ScriptEndTime, 126);

DECLARE @ScriptElapsedSeconds INT =
    DATEDIFF(SECOND, @ScriptStartTime, @ScriptEndTime);
DECLARE @ScriptElapsedMinutes INT = @ScriptElapsedSeconds / 60;
DECLARE @ScriptRemainingSeconds INT = @ScriptElapsedSeconds % 60;

PRINT 'Projects script duration (seconds): ' +
    CONVERT(VARCHAR(30), @ScriptElapsedSeconds);

PRINT 'Projects script duration (minutes:seconds): ' +
    CONVERT(VARCHAR(30), @ScriptElapsedMinutes) + 'm ' +
    CONVERT(VARCHAR(30), @ScriptRemainingSeconds) + 's';

PRINT 'Final Projects tables: PKTable2, PKTable';
