# Future Breakdown of Cohort

- So I previously got all 1.2 million Crohn's PatientDurableKeys,in the recipe PatientWithDx. I now want to upload that and then get lots more info - med tables, visit tables, etc. Given the size, I thought it was going to be a huge upload, taking a long time, and that it be a major time sink in relation to doing a large poll. It turns out that it wasn't the case. It took about two minutes to do the upload of 1.2 million rows with probably ten columns. I think this changes our paradigm of trying to get the whole cohort together.

  - Previous wisdom was that if I had a multiplier I should do all the runs of one cohort together while Cosmos connection is still up. Now I see I don't have to - I could do somethign as simple as a new open connection every table if I wanted to -

  - Right now I have the Crones HXDX etc YAML going and it is been hours and I have not gotten any update on how it's doing because the entire batch is pulling multiple different tables with a bunch of joints. So from a progress reading standpoint this isn't very useful. And while I appreciate that all of them are going within one cosmos connection, it leads to a lack of information on how progress is going.

  - So now I'm wondering if we can really do batching by sort of like a subject area instead of doing it by everyone needing the same open cohort connection. I don't think that I would ask you to do the batching by decision of what sort of is to be batched together. I think that what we can do is in recipes I can make specific mega recipes like medication info, visit info, birthing info, things that tend to have two or three different tables that are connected to each other in some way. I could have that as sort of a a recipe instead of just being a single table.

- I think this is a little more like what I had intended to do in the original set, but was afraid of the sort of cohort upload block being this huge delay. I think now we can look at it more flexibly. Say there are 9 tables, 3 in a birth block (birth fact, mother info, pregnancy fact/dim), 3 in a med block (med order, admin, dispense), visits block (edvisits, hospitaladmissions, etc.). Say I have a multiplier of, say, 'IBD' - UC, Crohns. Well if I get the PK table for all of UC, then I can move through the three blocks as their own batch, so that way we can say "getting UC Meds block" instead of "getting all UC data". I actually think this may be a bit confustin because it's kind of confusing when you have 'separate tables' meaning that the splitter duplicates the tables for a new splitter variable. Instead, that should be renamed to 'separate PKs per splitter', or somethign like that. Then, this table batch option could be 'group tables into a batch' and then once it's opened, you can just add different groups, give them a group name, and then it has an 'add table to group' oand 'remove table from group' and 'remove group' buttons. It should say that 'anything left over will be its own group batch' or something.

  - I think this is low priority right now - i want to ensure the current features work first. To that end, tell me your questions, but once we have mutual understanding, this should be added to 'roadmap' and deleted rather than waiting for implementation.