-- NOTE: transcribed from the real generated script. Earlier copies of this
-- fixture carried OCR damage that was mistaken for generator bugs; see
-- pullmanager_contracts.md.
-- Note: Cosmos-side OPENQUERY staging script written by generative AI

USE COSMOS;  -- COSMOS or COSMOS_SneakPeek as chosen in YAML

-- Server name for use in OPENQUERY (Projects script)
SELECT @@SERVERNAME AS CosmosServerName;

-- No upload_cohorts defined; no upload switch variables declared.

-- Phase 0: upload_cohorts (PROJECTS / CSV / parquet -> Cosmos global temps)
-- No upload cohorts defined; no upload blocks generated.

-- Cohort pull switches (1 = pull, 0 = skip)
DECLARE @PullPKTable2 INT = 1;
DECLARE @PullPKTable INT = 1;

-- Phase 1: schema for all global temp tables
-- Schema for global temp: PKTable (PKTable2) -> ##JVM_PKTable2
DROP TABLE IF EXISTS ##JVM_PKTable2;

CREATE TABLE ##JVM_PKTable2
(
    PatientDurableKey BIGINT NOT NULL
);

-- Schema for global temp: PKTable (PKTable) -> ##JVM_PKTable
DROP TABLE IF EXISTS ##JVM_PKTable;

CREATE TABLE ##JVM_PKTable
(
    DiagnosisEventKey BIGINT NOT NULL,
    PatientDurableKey BIGINT NOT NULL,
    EncounterKey BIGINT NOT NULL,
    StartDateKey INT NOT NULL,
    BillingCodeValue VARCHAR(400) NULL,
    BillingCodeType VARCHAR(100) NULL
);

-- Phase 2: per-cohort execution (population + telemetry)
-- Execution block for cohort: PKTable2 (PKTable2)
IF (@PullPKTable2 = 1)
BEGIN
    DECLARE @StartTime_PKTable2 DATETIME2 = SYSDATETIME();

    /*
      Generated by Python (Kilo code, PK-simple) from simplified cohorts YAML
      Cohort (Cosmos): PKTable (PK)
      Destination global temp: ##JVM_PKTable2
      Source: COSMOS.COSMOS.dbo
    */

    -- [PKTable2\Cosmos-filter] Counting raw source rows (approximate total
    -- before filtering)
    SELECT
        'PKTable2' AS CohortName,
        'PKTable2' AS DestTable,
        'source raw' AS CountType,
        COUNT_BIG(1) AS [PKTable2RowCount]
    FROM dbo.PatientDim AS p;

    -- No dedup_keys configured; using raw staged cohort rows as-is.

    -- Raw staging from Cosmos (no deduplication)
    INSERT INTO ##JVM_PKTable2 (PatientDurableKey)
    SELECT TOP (500)
        p.DurableKey AS PatientDurableKey
    FROM dbo.PatientDim AS p
    WHERE
        p._IsDeleted = 0
        AND p.IsCurrent = 1
        AND p.UseInCosmosAnalytics_X = 1
        AND p.DurableKey IS NOT NULL
    ;

    DECLARE @EndTime_PKTable2 DATETIME2 = SYSDATETIME();

    DECLARE @ElapsedSeconds_PKTable2 INT =
        DATEDIFF(SECOND, @StartTime_PKTable2, @EndTime_PKTable2);
    DECLARE @ElapsedMinutes_PKTable2 INT = @ElapsedSeconds_PKTable2 / 60;
    DECLARE @RemainingSeconds_PKTable2 INT = @ElapsedSeconds_PKTable2 % 60;

    SELECT
        'PKTable2' AS CohortName,
        'PKTable2' AS DestTable,
        @StartTime_PKTable2 AS CohortStartTime,
        @EndTime_PKTable2 AS CohortEndTime,
        @ElapsedSeconds_PKTable2 AS CohortDurationSeconds,
        @ElapsedMinutes_PKTable2 AS CohortDurationMinutes,
        @RemainingSeconds_PKTable2 AS CohortDurationRemainingSeconds,
        COUNT(*) AS CohortRowCount
    FROM ##JVM_PKTable2;
END;

-- Execution block for cohort: PKTable (PKTable)
IF (@PullPKTable = 1)
BEGIN
    DECLARE @StartTime_PKTable DATETIME2 = SYSDATETIME();

    /*
      Generated by Python (Kilo code, PK-simple) from simplified cohorts YAML
      Cohort (Cosmos): PKTable (PK)
      Destination global temp: ##JVM_PKTable
      Source: COSMOS.COSMOS.dbo
    */

    -- [PKTable\Cosmos-filter] Counting raw source rows (approximate total
    -- before filtering)
    SELECT
        'PKTable' AS CohortName,
        'PKTable' AS DestTable,
        'source raw' AS CountType,
        COUNT_BIG(1) AS [PKTableRowCount]
    FROM dbo.DiagnosisEventFact AS def;

    -- No dedup_keys configured; using raw staged cohort rows as-is.

    -- Raw staging from Cosmos (no deduplication)
    INSERT INTO ##JVM_PKTable (DiagnosisEventKey, PatientDurableKey, EncounterKey,
        StartDateKey, BillingCodeValue, BillingCodeType)
    SELECT TOP (500)
        def.DiagnosisEventKey AS DiagnosisEventKey,
        def.PatientDurableKey AS PatientDurableKey,
        def.EncounterKey AS EncounterKey,
        def.StartDateKey AS StartDateKey,
        dt.Value AS BillingCodeValue,
        dt.Type AS BillingCodeType
    FROM dbo.DiagnosisEventFact AS def
    INNER JOIN DiagnosisTerminologyDim AS dt ON dt.DiagnosisKey = def.DiagnosisKey
    INNER JOIN ##JVM_PKTable2 AS p ON p.PatientDurableKey = def.PatientDurableKey
    WHERE
        def._IsDeleted = 0
        AND dt._IsDeleted = 0
        AND def.StartDateKey BETWEEN 20200101 AND 20260601
        AND dt.Type IN ('ICD-10-AM', 'ICD-10-CA', 'ICD-10-CM')
        AND (
            dt.Value LIKE 'K50.%'
            OR dt.Value = 'K50'
            OR dt.Value LIKE 'K51.%'
            OR dt.Value = 'K51'
        )
        AND def.DiagnosisEventKey IS NOT NULL
        AND def.PatientDurableKey IS NOT NULL
        AND def.EncounterKey IS NOT NULL
        AND def.StartDateKey IS NOT NULL
    ;

    DECLARE @EndTime_PKTable DATETIME2 = SYSDATETIME();

    DECLARE @ElapsedSeconds_PKTable INT =
        DATEDIFF(SECOND, @StartTime_PKTable, @EndTime_PKTable);
    DECLARE @ElapsedMinutes_PKTable INT = @ElapsedSeconds_PKTable / 60;
    DECLARE @RemainingSeconds_PKTable INT = @ElapsedSeconds_PKTable % 60;

    SELECT
        'PKTable' AS CohortName,
        'PKTable' AS DestTable,
        @StartTime_PKTable AS CohortStartTime,
        @EndTime_PKTable AS CohortEndTime,
        @ElapsedSeconds_PKTable AS CohortDurationSeconds,
        @ElapsedMinutes_PKTable AS CohortDurationMinutes,
        @RemainingSeconds_PKTable AS CohortDurationRemainingSeconds,
        COUNT(*) AS CohortRowCount
    FROM ##JVM_PKTable;
END;

-- Final Cosmos global temp tables for reference
SELECT
    '##JVM_PKTable2, ##JVM_PKTable' AS FinalCosmosGlobalTemps;